### ISSUE TITLE
Reconstructing missing test/new data

### ISSUE THREAD

**Issue by brudfors** [matthias-scholz/nonlinear-pca#1]
Hello @matthias-scholz,

Thank you for a nice package!

If I have data with missing values, separated into train/test, and I fit the model to the training data with `nlpca`, I can reconstruct the missing training data with `nlpca_get_data`; however, it does not seem straightforward to reconstruct the missing values in the test data. Still, the documentation says:

"`net` can be used in `nlpca_get_components` and `nlpca_get_data` to obtain component values (scores) for new data or reconstructed data for any component value."

But I have not been able to figure out how to reconstruct test/new data, is this not easily doable?

**Comment by matthias-scholz** [comment]
Missing data estimation works only in 'inverse' mode. 
And yes, training an inverse nlpca model and applying it to test data should work.

Model validation is an example of reconstructing missing data in a test data set:
http://www.nlpca.org/validation-of-nonlinear-PCA.html

FAQ
https://faq.nlpca.org/faq

**Comment by matthias-scholz** [comment]
Model validation is an example of reconstructing missing data in test data:
http://www.nlpca.org/validation-of-nonlinear-PCA.html

**Comment by brudfors** [comment]
Thanks @matthias-scholz, that first link showed exactly what I wanted to achieve, awesome!
